---
kind: Service
apiVersion: v1
metadata:
  name: cert-app
spec:
  selector:
    app: cert-app
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 80
      # Port to forward to inside the pod
      targetPort: 3000
      # Port accessible outside cluster
      nodePort: 30003
  type: LoadBalancer
 
 
 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-for-cert-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cert-app
    spec:
      containers:
        - name: cert-app
          image: mehranunicef/certapp:v1.0.0
          ports:
            - containerPort: 3000